---
- name: Criar pasta do Portainer
  file:
    path: /opt/portainer
    state: directory
    mode: '0755'

- name: Criar docker-compose.yml do Portainer
  template:
    src: docker-compose.yml.j2
    dest: /opt/portainer/docker-compose.yml

- name: Subir o Portainer com Docker Compose
  command: docker compose up -d
  args:
    chdir: /opt/portainer
