---
- name: Configurar servidor da aplicação
  hosts: hetzner
  become: true

  vars:
    docker_user: "rodrigodebiasiborghi"
    docker_image: "rodrigodebiasiborghi/supremo-api:2.2.13"
    docker_image_web: "rodrigodebiasiborghi/supremo-web:1.9.0"
    docker_image_integrador:
    domain_name: "borghidevops.site"
    email_ssl: "rodrigo.debiasiborghi@gmail.com"

  roles:
    - { role: docker, tags: ['docker'] }
    - { role: nginx, tags: ['nginx'] }
    - { role: app, tags: ['app'] }
    - { role: portainer, tags: ['portainer'] }